# Codecov configuration for Rivulet
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 0.5%
        informational: false

  # Ignore patterns - exclude test projects and generated files
  ignore:
    - "tests/**/*"              # Exclude all test projects
    - "**/*.Tests/**/*"         # Exclude any .Tests projects
    - "**/obj/**"               # Exclude build artifacts
    - "**/bin/**"               # Exclude build artifacts
    - "**/*.Designer.cs"        # Exclude designer files
    - "**/*.g.cs"               # Exclude generated files
    - "**/*.g.i.cs"             # Exclude generated files
    - "**/AssemblyInfo.cs"      # Exclude assembly info

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
