<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <!-- Packages -->
    <PackageVersion Include="System.Linq.Async" Version="7.0.1" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.12" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.12" />
    <PackageVersion Include="OpenTelemetry.Api" Version="1.18.0" />
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Polly" Version="8.7.0" />
    <PackageVersion Include="MySqlConnector" Version="2.6.2" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.3" />

    <!-- Tests -->
	<PackageVersion Include="Shouldly" Version="4.3.0" />
	<PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="10.0.12" />
	<PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
	<PackageVersion Include="xunit.v3" Version="4.0.1" />
	<PackageVersion Include="coverlet.collector" Version="10.0.1" />
	<PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
	<PackageVersion Include="OpenTelemetry" Version="1.18.0" />
	<PackageVersion Include="OpenTelemetry.Exporter.InMemory" Version="1.18.0" />
	<PackageVersion Include="OpenTelemetry.Exporter.Console" Version="1.18.0" />
	<PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
	<PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
	<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
	<PackageVersion Include="Testcontainers.MySql" Version="4.15.0" />
	<PackageVersion Include="Testcontainers.PostgreSql" Version="4.15.0" />
	<PackageVersion Include="Testcontainers.MsSql" Version="4.15.0" />

  </ItemGroup>
</Project>